name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build the Docker image
      run: docker build -t saqlaindoc/nodejsapp:${{ github.sha }} .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image
      run: docker push saqlaindoc/nodejsapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: ArgoCD Login
      run: |
        argocd login ${{ secrets.ARGOCD_SERVER }} --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure

    - name: Update ArgoCD Application Image
      run: |
        argocd app set node-express-app --repo https://github.com/25Saqlain/nodejs-argocd.git --path app --revision HEAD --values image.tag=${{ github.sha }}

    - name: Sync ArgoCD Application
      run: |
        argocd app sync node-express-app
